version: '3.6'
# Deploys MongoDB with customization scripts and container with Mongo client
#
# usage:
# sudo docker-compose build
# sudo docker-compose up


services:
  my-mongodb:
    image: mongo
    container_name: my-mongodb
    restart: always 
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
        MONGO_INITDB_DATABASE: ${DATABASE}
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      # seeding scripts
      #- ./entrypoint.sh:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - mongo_net
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always 
    env_file:
      - .env
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
        ME_CONFIG_MONGODB_SERVER: my-mongodb
        ME_CONFIG_MONGODB_PORT: "27017"
        ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
        ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - mongo_net
    depends_on:
      - my-mongodb

    
volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig:

networks:
  mongo_net:
    driver: bridge